(() => {
  'use strict';
  const KEY = 'batlas:firstVisitTour:v1';
  const steps = [
    {k:'Find boats that fit you',h:'Start with how you actually plan to use the boat',p:'Use Find Your Boat to think through cruising area, dimensions, hull behaviour, propulsion, features and crew needs before narrowing the field.'},
    {k:'Research real models',h:'Move from ideas to specific boat models',p:'B-Atlas model guides bring together specifications, dimensions, propulsion, cruising performance where evidence exists, practical trade-offs and inspection focus.'},
    {k:'Save and compare',h:'Keep promising candidates together',p:'Save models you want to investigate further, compare alternatives and keep notes as your shortlist changes.'},
    {k:'Keep looking',h:'Turn research into an ongoing Boat Watch',p:'Selected models can become a Boat Watch. You can also improve B-Atlas by contributing corrections, photos, manuals and ownership experience.'}
  ];
  let i=0;
  const el=(tag,cls,text)=>{const n=document.createElement(tag); if(cls)n.className=cls; if(text!=null)n.textContent=text; return n;};
  function mark(v='seen'){try{localStorage.setItem(KEY,v)}catch(e){}}
  function known(){try{return !!localStorage.getItem(KEY)}catch(e){return true}}
  function closeOverlay(){document.querySelector('.batlas-tour-overlay')?.remove(); document.body.style.overflow=''; mark('completed');}
  function renderStep(dialog){const s=steps[i]; dialog.querySelector('.batlas-tour-progress').textContent=`Step ${i+1} of ${steps.length}`; dialog.querySelector('.batlas-tour-kicker').textContent=s.k; dialog.querySelector('h2').textContent=s.h; dialog.querySelector('.batlas-tour-copy').textContent=s.p; const prev=dialog.querySelector('.batlas-tour-prev'); prev.hidden=i===0; const next=dialog.querySelector('.batlas-tour-next'); next.textContent=i===steps.length-1?'Finish':'Next';}
  function openTour(){document.querySelector('.batlas-tour-invite')?.remove(); document.querySelector('.batlas-tour-overlay')?.remove(); i=0; const ov=el('div','batlas-tour-overlay'); ov.setAttribute('role','presentation'); const d=el('div','batlas-tour-dialog'); d.setAttribute('role','dialog'); d.setAttribute('aria-modal','true'); d.setAttribute('aria-labelledby','batlasTourTitle'); const close=el('button','batlas-tour-close','×'); close.type='button'; close.setAttribute('aria-label','Close tour'); const progress=el('div','batlas-tour-progress'); const kicker=el('div','batlas-tour-kicker'); const h=el('h2'); h.id='batlasTourTitle'; const p=el('p','batlas-tour-copy'); const nav=el('div','batlas-tour-nav'); const prev=el('button','batlas-tour-prev','Previous'); prev.type='button'; const next=el('button','batlas-tour-next','Next'); next.type='button'; nav.append(prev,next); d.append(close,progress,kicker,h,p,nav); ov.append(d); document.body.append(ov); document.body.style.overflow='hidden'; renderStep(d); close.addEventListener('click',closeOverlay); ov.addEventListener('click',e=>{if(e.target===ov)closeOverlay()}); prev.addEventListener('click',()=>{if(i>0){i--;renderStep(d)}}); next.addEventListener('click',()=>{if(i<steps.length-1){i++;renderStep(d)}else closeOverlay()}); document.addEventListener('keydown',function esc(e){if(e.key==='Escape'&&document.body.contains(ov)){closeOverlay();document.removeEventListener('keydown',esc)}}); setTimeout(()=>next.focus(),0);}
  function invite(){if(known() || location.pathname!=='/') return; const box=el('aside','batlas-tour-invite'); box.setAttribute('aria-labelledby','batlasTourInviteTitle'); const h=el('h2',null,'New to B-Atlas?'); h.id='batlasTourInviteTitle'; const p=el('p',null,'See how to find, research, save and watch boat models in about 60 seconds.'); const acts=el('div','batlas-tour-actions'); const start=el('button','batlas-tour-start','Start tour'); start.type='button'; const dismiss=el('button','batlas-tour-dismiss','Not now'); dismiss.type='button'; acts.append(start,dismiss); box.append(h,p,acts); document.body.append(box); start.addEventListener('click',openTour); dismiss.addEventListener('click',()=>{mark('dismissed');box.remove()});}
  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('openBatlasTour')?.addEventListener('click',openTour); window.setTimeout(invite,900)});
})();
